org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.projectcachedir=.gradle.nosync

# Device-Owner-App kann nicht deinstalliert werden – Testlauf lässt APKs installiert
android.injected.androidTest.leaveApksInstalledAfterRun=true
